### ISSUE TITLE
Elixir support broken

### ISSUE THREAD

**Issue by econnolly** [processone/fast_xml#11]
Hi guys,

The latest version (1.1.14), while it now successfully creates the Erlang beam files using the latest Elixir 1.3 tooling, doesn't appear to produce the Elixir.FastXML*.beam files any more.

Edward

**Comment by cesarizu** [comment]
As a workaround, declaring the dependency like: `{:fast_xml, github: "processone/fast_xml"}` makes it work.

**Comment by cesarizu** [comment]
Just an update of the current situation as I see it:

The last version that supports elixir is 1.1.20, when declared like this: `{:fast_xml, github: "processone/fast_xml", tag: "1.1.20"}`. The version from hex doesn't work. Any new version is failing because of processone/fast_xml#22.

To use a newer version, I've tried to declare the dependency on my project like this:

`{:fast_xml, github: "processone/fast_xml", manager: :rebar3}`

And:

`{:fast_xml, "~> 1.1.23", manager: :rebar3}`

Both forms compile, but don't generate the Elixir.FastXML*.beam files.

**Comment by cromain** [comment]
1.1.27 is now packaged and include fix for #22.
Closing this issue as it should be resolved now.

**Comment by hrefhref** [comment]
The problem seems to still happen ? Tried today.

If using `{:fast_xml, "~> 1.1.30"}` the Elixir modules are not compiled; from git it works.
